services:
  resume-real:
    build: .
    volumes:
      - ./build:/build
    command: ["node", "generate-resume.js", "real"]

  resume-anon:
    build: .
    volumes:
      - ./build:/build
    command: ["node", "generate-resume.js", "anon"]

  cover-letter-real:
    build: .
    volumes:
      - ./build:/build
    command: ["node", "generate-cover-letter.js", "real"]

  tsc-watch:
    build: .
    volumes:
      - ./src:/app/src
    command: ["npx", "tsc", "--watch", "--preserveWatchOutput"]
    profiles: ["dev"]
